---
- name: Install Docker and Docker Compose # AltLinux
  package:
    name:
      - docker-cli
      - docker-engine
      - docker-compose-v2
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes