---
- name: Creating GitLab user and group
  import_tasks: user.yml

- name: Installing Docker and Docker Compose
  import_tasks: docker_installation.yml

- name: Configuring GitLab
  import_tasks: gitlab_configuration.yml

- name: Launching GitLab
  import_tasks: launch.yml