---
- name: Create SSL directory for Nginx
  file:
    path: "{{ nginx_path }}/ssl"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0755'
  when: enable_ssl

- name: Copy SSL certificate to Nginx
  copy:
    src: ssl.crt
    dest: "{{ nginx_path }}/ssl/gitlab.crt"
  when: enable_ssl
  notify: Reload Nginx

- name: Copy SSL key to Nginx
  copy:
    src: ssl.key
    dest: "{{ nginx_path }}/ssl/gitlab.key"
  when: enable_ssl
  notify: Reload Nginx

- name: Add GitLab configuration to Nginx
  template:
    src: nginx_gitlab.conf.j2
    dest: "{{ nginx_path }}/conf.d/gitlab.conf"
  notify: Reload Nginx

- name: Ensure GitLab configuration is included in Nginx
  lineinfile:
    path: "{{ nginx_path }}/nginx.conf"
    line: 'include {{ nginx_path }}/conf.d/gitlab.conf;'
    insertafter: 'http {'
    state: present
  notify: Reload Nginx