---
- name: Install PostgreSQL
  package:
    name:
      - "postgresql{{ postgres_version }}-server"
      - "postgresql{{ postgres_version }}-contrib"
    state: present

- name: Initialize the PostgreSQL system database
  shell: /etc/init.d/postgresql initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true

- name: Ensure PostgreSQL is listening on all addresses
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"

- name: Allow external connections to PostgreSQL
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: 'host all all 0.0.0.0/0 md5'
    state: present

- name: Create GitLab database
  postgresql_db:
    name: "{{ psql_database }}"
    state: present

- name: Create GitLab database user
  postgresql_user:
    name: "{{ psql_username }}"
    password: "{{ psql_password }}"
    db: "{{ psql_database }}"
    priv: "ALL"
    state: present

- name: Create btree_gist extension
  postgresql_ext:
    name: btree_gist
    db: "{{ psql_database }}"
    state: present

- name: Grant privileges on schema public to gitlab user
  postgresql_privs:
    db: "{{ psql_database }}"
    role: "{{ psql_username }}"
    type: schema
    privs: "USAGE,CREATE"
    objs: "public"
    state: present

- name: Ensure the PostgreSQL service is restarted
  service:
    name: postgresql
    state: restarted