---
- name: Create GitLab group
  group:
    name: "{{ gitlab_group }}"
    system: yes

- name: Create GitLab user
  user:
    name: "{{ gitlab_user }}"
    system: yes
    shell: /usr/sbin/nologin
    group: "{{ gitlab_group }}"