---
####################################
############# VERSIONS #############
####################################

# Версии для GitLab и Redis - версии Docker-образов
gitlab_ce_version: latest
redis_version: latest

# Версия для PostgreSQL - версия potgres-server в репозиториях AltLinux
postgres_version: 16


#####################################
######## SYSTEM USERS/GROUPS ########
#####################################

# Системные пользователь и группа для установки GitLab
gitlab_user: gitlab
gitlab_group: gitlab

# Системные пользователь и группа, которые управляют внешним Nginx
nginx_user: nginx
nginx_group: nginx


#####################################
######## POSTGRESQL SETTINGS ########
#####################################

# Включение/отключение внешнего PostgreSQL
gitlab_external_postgres: true

# Пользователь; пароль пользователя; название БД
psql_username: "super_user"
psql_password: "secure_password"
psql_database: "gitlab_db"


#####################################
########## GITLAB SETTINGS ##########
#####################################

# Адрес, который используется для формирования ссылок внутри GitLab, а также указывается в Nginx
gitlab_external_url: "gitlab.example.com"

# Порты контейнера для доступа к GitLab
gitlab_container_port: 8484
gitlab_container_ssh_port: 2424

# Путь установки необходимых файлов для GitLab (путь не в контейнере, а конкретно на хосте!)
gitlab_repo_path: "/srv/gitlab"

# Пароль для root пользователя GitLab
gitlab_root_password: "super_password"


####################################
########## NGINX SETTINGS ##########
####################################

# Включение/отключение внешнего Nginx
gitlab_external_nginx: true

# Путь, по которому установлен Nginx на внешнем хосте
nginx_path: "/etc/nginx"

# Включение/отключение SSL
enable_ssl: false

# Пути, по которым надо установить SSL-сертификаты на внешнем хосте
ssl_certificate_path: "{{ nginx_path }}/ssl/gitlab.crt"
ssl_certificate_key_path: "{{ nginx_path }}/ssl/gitlab.key"


#####################################
########### LDAP SETTINGS ###########
#####################################

# Включение/отключение внешнего LDAP
gitlab_external_ldap: true

# Конфигурация доступа к LDAP
ldap_bind_params:
  host: "ldap.example.com"
  port: 389
  uid: "sAMAccountName"
  bind_dn: "cn=binduser,dc=example,dc=com"
  password: "bindpassword"
  encryption: "plain"
  base: "dc=example,dc=com"
  verify_certificates: false


####################################
########## MINIO SETTINGS ##########
####################################

# Включение/отключение внешнего MinIO
gitlab_external_minio: true

# Расположение MinIO
minio_endpoint: "http://minio.example.com"

# Login/Password для доступа к MinIO
minio_access_key: "super_login"
minio_secret_key: "secret_pass"

# Bucket-ы, которые будут использоваться GitLab-ом (предварительно должны быть уже созданы в MinIO!)
minio_buckets:
  artifacts: "gitlab-artifacts"
  external_diffs: "gitlab-diffs"
  lfs: "gitlab-lfs"
  uploads: "gitlab-uploads"
  packages: "gitlab-packages"
  dependency_proxy: "gitlab-dependency-proxy"
  terraform_state: "gitlab-terraform-state"
  ci_secure_files: "gitlab-ci-secure-files"
  pages: "gitlab-pages"
