---
####################################
############# VERSIONS #############
####################################

# Версии для GitLab и Redis - версии Docker-образов
gitlab_ce_version: latest
redis_version: latest

# Версия для PostgreSQL - версия potgres-server в репозиториях AltLinux
postgres_version: 16


#####################################
######## SYSTEM USERS/GROUPS ########
#####################################

# Системные пользователь и группа для установки GitLab на хосте
gitlab_user: gitlab
gitlab_group: gitlab


#####################################
########## GITLAB SETTINGS ##########
#####################################

# Адрес, который используется для формирования ссылок внутри GitLab
# Также этот адрес должен указывается в вашем внешнем Reverse Proxy
gitlab_external_url: "gitlab.example.com"

# Включение/отключение SSL
# Если GitLab будет стоять за внешнем Reverse Proxy и принимать трафик по HTTPS, то следует включить SSL
enable_ssl: true

# Внешние порты контейнера для доступа к GitLab
gitlab_container_port: 8484
gitlab_container_ssh_port: 2424

# Путь установки необходимых файлов для GitLab (путь не в контейнере, а конкретно на хосте!)
gitlab_repo_path: "/data/gitlab"

# Первоначальный пароль для root-пользователя GitLab
gitlab_root_password: "super_password"


#####################################
######## POSTGRESQL SETTINGS ########
#####################################

# Включение/отключение внешнего PostgreSQL
gitlab_external_postgres: true

# Данные для подключения к БД
psql_host: "postgres.example.com"
psql_port: "5432"
psql_username: "gitlab_user"
psql_password: "gitlab_password"
psql_database: "gitlab_db"


#####################################
######### KEYCLOAK SETTINGS #########
#####################################

# Включение/отключение внешнего Keycloak
# Keycloak поддерживается только при https подключении
gitlab_external_keycloak: true

# Адрес Keycloak
keycloak_issuer: "keycloak.example.com"

# Realm (пространство) Keycloak
keycloak_realm: "name"

# Название клиента GitLab в Keycloak-пространстве и его Secret
keycloak_client_name: "gitlab"
keycloak_client_secret: "SomeMegaSuperSecretGeneratedByKC"


#####################################
########### LDAP SETTINGS ###########
#####################################

# Включение/отключение внешнего LDAP
gitlab_external_ldap: true

# Конфигурация доступа к LDAP
ldap_bind_params:
  host: "ldap.example.com"
  port: 389
  uid: "sAMAccountName"
  bind_dn: "cn=binduser,dc=example,dc=com"
  password: "bindpassword"
  encryption: "plain"
  base: "dc=example,dc=com"
  verify_certificates: false


####################################
########## MINIO SETTINGS ##########
####################################

# Включение/отключение внешнего MinIO
gitlab_external_minio: true

# Адрес MinIO
minio_endpoint: "http://minio.example.com"

# Login/Password для доступа к MinIO
minio_access_key: "super_login"
minio_secret_key: "secret_pass"

# Bucket-ы, которые будут использоваться GitLab-ом (предварительно должны быть уже созданы в MinIO!)
minio_buckets:
  artifacts: "gitlab-artifacts"
  external_diffs: "gitlab-diffs"
  lfs: "gitlab-lfs"
  uploads: "gitlab-uploads"
  packages: "gitlab-packages"
  dependency_proxy: "gitlab-dependency-proxy"
  terraform_state: "gitlab-terraform-state"
  ci_secure_files: "gitlab-ci-secure-files"
  pages: "gitlab-pages"
