---
####################################
############# VERSIONS #############
####################################

gitlab_ce_version: latest
postgres_version: 16
redis_version: latest


####################################
########### USERS/GROUPS ###########
####################################

gitlab_user: gitlab
gitlab_group: gitlab

nginx_user: nginx
nginx_group: nginx

psql_user: postgres
psql_group: postgres


#####################################
######## POSTGRESQL SETTINGS ########
#####################################

gitlab_external_postgres: true
psql_username: "super_user"
psql_password: "secure_password"
psql_database: "gitlab_db"


#####################################
########## GITLAB SETTINGS ##########
#####################################

gitlab_repo_path: "/srv/gitlab"
gitlab_root_password: "super_password"


####################################
########## NGINX SETTINGS ##########
####################################

gitlab_external_nginx: false
gitlab_nginx_server_name: "gitlab.example.com"
nginx_path: "/etc/nginx"

enable_ssl: false
ssl_certificate_path: "{{ nginx_path }}/ssl/gitlab.crt"
ssl_certificate_key_path: "{{ nginx_path }}/ssl/gitlab.key"


#####################################
########### LDAP SETTINGS ###########
#####################################

gitlab_external_ldap: false
ldap_bind_params:
  host: "ldap.example.com"
  port: 389
  uid: "sAMAccountName"
  bind_dn: "cn=binduser,dc=example,dc=com"
  password: "bindpassword"
  encryption: "plain"
  base: "dc=example,dc=com"
  verify_certificates: false


####################################
########## MINIO SETTINGS ##########
####################################

gitlab_external_minio: false
minio_access_key: ""
minio_secret_key: ""